export SPARK_DIST_CLASSPATH=$(/usr/local/hadoop/bin/hadoop classpath)
export SPARK_CLASSPATH=$SPARK_CLASSPATH:/usr/local/spark/lib/http/*
export SPARK_CLASSPATH=$SPARK_CLASSPATH:/usr/local/spark/lib/hbase/*:/usr/local/hbase/conf
export SPARK_CLASSPATH=$SPARK_CLASSPATH:/usr/local/spark/lib/kafka/*
export SPARK_CLASSPATH=$SPARK_CLASSPATH:/usr/local/spark/mysql-connector-java-5.1.40/*
export SPARK_CLASSPATH=$SPARK_CLASSPATH:/usr/local/spark/lib/datanucleus/*
export SPARK_CLASSPATH=$SPARK_CLASSPATH:/usr/local/spark/lib/hive/*
export SPARK_CLASSPATH=$SPARK_CLASSPATH:/usr/local/spark/lib/hbrdd/*
export SPARK_EXECUTOR_MEMORY=2000M
export SPARK_DRIVER_MEMORY=2500M
